function editcreatoroptions()
{
  document.getElementById('spancreatorname').style.display='none';
  document.getElementById('spanemail').style.display='none';
  document.getElementById('spanphoneno').style.display='none';
  document.getElementById('spanwebsite').style.display='none';
  document.getElementById('spanskills').style.display='none';
  document.getElementById('spanlinkedin').style.display='none';
  document.getElementById('spanindustry').style.display='none';
  document.getElementById('spaneducation').style.display='none';
  document.getElementById('spanexp').style.display='none';
  document.getElementById('changepassword').style.display='none';
  document.getElementById('editaccount').style.display='none';

  document.getElementById('txtcreatorname').style.display='block';
  document.getElementById('txtemail').style.display='block';
  document.getElementById('txtphoneno').style.display='block';
  document.getElementById('txtwebsite').style.display='block';
  document.getElementById('txtskills').style.display='block';
  document.getElementById('txtlinkedin').style.display='block';
  document.getElementById('txtindustry').style.display='block';
  document.getElementById('txaeducation').style.display='block';
  document.getElementById('txaexp').style.display='block';
  document.getElementById('currentpassword').style.display='block';
  document.getElementById('txtcurrentpassword').style.display='block';
  document.getElementById('changedpassword').style.display='block';
  document.getElementById('txtchangedpassword').style.display='block';
  document.getElementById('editbutton').style.display='block';
  document.getElementById('deletebutton').style.display='block';
}
